# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8009

# mysql config
mysql:
  host: "127.0.0.1"
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: "mp_main"
  username: "root"
  password: "123456"
  port: 3306
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: true

# qiniu config
qiniu:
  zone: "mp_main"
  bucket: ""
  local: "/upload/"
  img-path: ""
  use-https: false
  access-key: ""
  secret-key: ""
  use-cdn-domains: false

# baidu ai
baidu-ai:
  app-key: ''
  app-secret-key: ''